### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by bladner272** [jra457/Group-6#32]
Handling of creating a new user and adding it to a database.

**Comment by jra457** [comment]
Registration and login/logout implemented with user authentication and assigning the user to either the "Seller" or "Customer" group to edit their view. Forms have built in validation requiring all fields to be properly filled in with feedback provided on invalid input.

**Comment by jra457** [comment]
Registration and login/logout implemented with user authentication and assigning the user to either the "Seller" or "Customer" group to edit their view. Forms have built in validation requiring all fields to be properly filled in with feedback provided on invalid input.
